#!/usr/bin/env python3

import requests
import json
import gzip


def titles():
    of = 't-s'  # 出力項目：タイトル, あらすじ
    lim = '100'  # 出力数：1~500
    out = 'json'  # 出力形式
    g_zip = '5'  # gzip圧縮レベル/ここgzipと干渉していたので_付け足し
    order = 'weekly'  # 出力順序：週間ユニークアクセスが多い順
    biggenre = '2'  # ジャンル「異世界」を指定
    url = 'https://api.syosetu.com/novelapi/api/?' + 'of=' + of + '&' + 'lim' + lim + '&' + 'out=' + \
        out + '&' + 'gzip=' + g_zip + '&' + 'order=' + \
        order + '&' + 'biggenre=' + biggenre

    response = requests.get(url)  # responceオブジェクトを生成
    response.encoding = 'gzip'  # encodeingを指定
    r = response.content  # バイナリ形式で取得
    res_content = gzip.decompress(r).decode("utf-8")  # gzip展開, UTF-8
    response_json = json.loads(res_content)  # jsonのデコーディング

    print(response_json)


titles()
